version: "3.8"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_db
    restart: always
    environment:
      SA_PASSWORD: "MinhaSenha123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    networks:
      - minha-rede
    volumes:
      - sqlserver_data:/var/opt/mssql

  api:
    build: ./api
    container_name: api_csharp
    environment:
      - Server=DESKTOP-T4HMQME;Database=teste-lab;Integrated Security=True;TrustServerCertificate=True;
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - minha-rede

  worker:
    build: ./worker
    container_name: worker_csharp
    environment:
      - Server=DESKTOP-T4HMQME;Database=teste-lab;Integrated Security=True;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - minha-rede

  frontend:
    build: ./frontend
    container_name: frontend_app
    environment:
      - REACT_APP_API_URL=http://api:5000
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge

volumes:
  sqlserver_data:
